### ISSUE TITLE
refractor

### ISSUE THREAD

**Issue by wooorm** [sergioramos/remark-prism#26]
a lot of the work you’re doing in this plugin is already done by refractor, you might want to check that out! https://github.com/wooorm/refractor

**Comment by sergioramos** [comment]
that is really helpful, will definitely test a change to take advantage the work done by refractor 👌

**Comment by wooorm** [comment]
It indeed doesn’t, the reason is that prism plugins are highly coupled to the DOM. Most folks can do without them, and then it’s much faster with refractor. Although, as you know, refractor results in an AST, so there could be alternatives built on the AST instead of DOM level!

**Comment by sergioramos** [comment]
After looking at refractor and it's trade-offs I still wanted to be able to use plugins in a _safe_ way. I did like that returns a tree rather than strings (like I was mostly doing).

So I re-wrote large chunks of this module to work more like refractor, but still allow to use plugins: https://github.com/sergioramos/remark-prism/commit/6f5da71e202081f1b86930d86c8c365cd8fdcc1f

Again, thank you for your suggestion 👍
